name: Haskell lab3 tests

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4.8'
          enable-stack: true
          stack-version: 'latest'
      - name: install hlint
        run: stack install hlint
      - name: run lint
        run: hlint src/*.hs

  format:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4.8'
          enable-stack: true
          stack-version: 'latest'
      - name: install ormolu
        run: stack install ormolu
      - name: auto format
        run: ormolu -i src/*.hs
      - name: run formatter checks
        run: ormolu --mode check src/*.hs


  test:
    needs: [format]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4.8'
          enable-stack: true
          stack-version: 'latest'
      - run: stack test